config/routes.rb
Rails.application.routes.draw do

  root 'members/homes#top'

  namespace :members do
    resources :destinations, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :show, :new, :create]
    post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
    get 'success' => 'orders#success', as: 'success'
    delete 'basket_products/alldestroy' => 'basket_products#alldestroy', as: 'basket_products_alldestroy'
    resources :basket_products, only: [:index, :create, :update, :destroy]
    resources :products, only: [:index, :show]
    get 'members/leave' => 'members#leave', as: 'members_leave'
    get 'homes/about' => 'homes#about', as:'homes_about'
    patch "members" => "members#destroy_update"
    resources :members, only: [:show, :edit, :update]
   end

  namespace :admins do
    get 'orders/top' => 'orders#top', as:'orders_top'
    resources :members, only: [:index, :show, :edit, :update]
    resources :productstypes, only: [:index, :edit, :create, :update]
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_products, only: [:update]

  end

  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
  }

  devise_for :members, controllers: {
      sessions:      'members/sessions',
      passwords:     'members/passwords',
      registrations: 'members/registrations'
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :basket_products, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :member, optional: true
	has_many :order_products, dependent: :destroy
	
	enum order_status: {
		入金待ち: 0,
		入金確認: 1,
		製作中: 2,
		発送準備中: 3,
		発送済み: 4
	}
end

app/controllers/admins/members_controller.rb
class Admins::MembersController < ApplicationController
  def index
  		@members = Member.page(params[:page])
  end

  def show
  		@member = Member.find(params[:id])
  end

  def edit
  		@member = Member.find(params[:id])
  end

  def update
  		@member = Member.find(params[:id])
  		@member.update(member_params)
  		redirect_to admins_member_path(@member)
  end

  private
  def member_params
  		params.require(:member).permit(:last_name, :first_name, :last_kana_name,
  		 :first_kana_name, :post_number, :address , :telephone_number, :email ,
  		  :member_status)
  end

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  def top
    @order = Order.all
  end

  def index
  	@order = Order.page(params[:page])
  end

  def show
  	@order = Order.find(params[:id])
  end

  def update
  	@order = Order.find(params[:id])
  	@order.update(order_params)
    if @order.order_status == "入金確認"
      @order.order_products.each do |op|
        op.update(production_status: 1)
      end
    end
   	redirect_to admins_order_path(@order.id)
  end

  private
	def order_params
		params.require(:order).permit(:order_status)
	end
end

app/controllers/members/basket_products_controller.rb
class Members::BasketProductsController < ApplicationController
  def index
  	@basket_products = current_member.basket_products
    @total_price = @basket_products.sum(&:sub_total)
  end

  def create
  	@basket_product = BasketProduct.new(basket_product_params)
  	@basket_product.member_id = current_member.id
  	@basket_product.save
  	  redirect_to members_basket_products_path, success: "商品をカートに追加しました。"
  end

  def update
  	@basket_product = BasketProduct.find(params[:id])
  	if @basket_product.update(basket_product_params)
  	   redirect_to members_basket_products_path, success: "個数を変更しました。"
  	else
  		render :index, danger: "個数の変更に失敗しました。"
  	end
  end

  def destroy
  	@basket_product = BasketProduct.find(params[:id])
  	if @basket_product.destroy
  	     redirect_to members_basket_products_path, success: "商品の削除が完了しました。"
  	else
  		render :index, danger: "商品の削除ができませんでした。"
  	end
  end

  def alldestroy
  	@basket_products = BasketProduct.where(member_id: current_member.id)
    if @basket_products.destroy_all
  	   redirect_to members_basket_products_path, success: "全商品の削除が完了しました。"
  	else
  		render :index, danger: "全商品の削除ができませんでした。"
  	end
  end

  private
  def basket_product_params
    params.require(:basket_product).permit(:member_id, :product_id, :quantity)
  end

end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/destinations_controller.rb
class Members::DestinationsController < ApplicationController
  def index
  	@dest_new = Destination.new
  	@dests = Destination.all
  end

  def create
  	@dest_new = Destination.new(dest_params)
    # saveする際に必要なmember_idを取得するためのアクションです
    @dest_new.member_id = current_member.id
  	if @dest_new.save
	  	redirect_to members_destinations_path
		else
			render :index
		end
  end

  def edit
  	@dest = Destination.find(params[:id])
  end

  def update
  	@dest = Destination.find(params[:id])
  	if @dest.update(dest_params)
  		redirect_to members_destinations_path
  	else
  		render :edit
  	end
  end

  def destroy
		dest = Destination.find(params[:id])
    dest.destroy
    redirect_to members_destinations_path
  end

  private
  def dest_params
		# params.require(:destination).permit(:id, :post_address, :address, :full_name)
    # member_idはコントローラのアクションで取得します
    params.require(:destination).permit(:post_address, :address, :full_name)
  end
end

app/controllers/members/homes_controller.rb
class Members::HomesController < ApplicationController
  def top
  	@types = ProductsType.all
  	@product_1 = Product.find(1)
  	@product_2 = Product.find(2)
  	@product_3 = Product.find(3)
  	@product_4 = Product.find(4)
  end

  def about
  end
end

app/controllers/members/members_controller.rb
class Members::MembersController < ApplicationController
  def show
  		@member = Member.find(current_member.id)
  end

  def edit
  		@member = Member.find(params[:id])
  end

  # 追加しました[member/members/:id/edit_update]＿りのじ
  def update
  		@member = Member.find(params[:id])
  		if @member.update(member_params)
  			redirect_to members_member_path(@member), notice: "successfully"
  		else
  			render "members/members/edit"
  		end
  end

  def leave
    @member = Member.find(current_member.id)
  end

  def destroy_update
    member = Member.find(current_member.id)
    member.update(member_status: true)
    reset_session
    redirect_to root_path
  end

  # 追加しました[member/members/:id/edit_update]＿りのじ ストロングパラメーター
  private
  def member_params
  		params.require(:member).permit(:last_name, :first_name, :last_kana_name, :first_kana_name, :email, :post_number, :telephone_number, :address)
  end

end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/orders_controller.rb
class Members::OrdersController < ApplicationController
  def index
    @order = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order_new = Order.new
    @members = Member.all
    @dest = Destination.new
  end

  def create
    @order = Order.new(order_set)
    if @order.save!
      current_member.basket_products.each do |basket|
        @price = basket.product.unit_price * basket.quantity
        @order_products = OrderProduct.new(
          product_id: basket.product.id,
          quantity_purchased: basket.quantity,
          price_at_purchase: @price,
          order_id: @order.id)
        
        @order_products.save!
      end
      current_member.basket_products.destroy_all
    end
    redirect_to members_success_path
  end

  def confirm
    @price_array = []
    @total_array = []
    @order = Order.new
    if params[:payment_method] == 'true'
      @order.payment_method = true
    else
      @order.payment_method = false
    end
    @user = Member.find(current_member.id)

    if params[:address_option] == "0"
      @post = @user.post_number
      @address = @user.address
      @name = @user.last_name + @user.first_name
    elsif params[:address_option] == "1"
      @destination = Destination.find(dest_set[:id])
      @post = @destination.post_address
      @address = @destination.address
      @name = @destination.full_name
    elsif params[:address_option] == "2"
      @new_destination = Destination.new(dest_params)
      @post = @new_destination.post_address
      @address = @new_destination.address
      @name = @new_destination.full_name

      @destination = Destination.new(
        member_id: current_member.id,
        address: @post,
        post_address: @address,
        full_name: @name)
      @destination.save!
    end
  end

  def success
  end

  private
  def order_set
    params.require(:order).permit(:member_id, :request_amount, :payment_method, :address, :post_address, :full_name)
  end

  def dest_set
    params.permit(:id)
  end

  def dest_params
    params.permit(:member_id, :address, :post_address, :full_name)
  end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/products_controller.rb
class Members::ProductsController < ApplicationController
  def index
    @products = Product.where(products_type_id: params[:products_type_id])
  	@quantity = @products.count
  	@types = ProductsType.all
  end

  def show
  	@product = Product.find(params[:id])
  	@basket_product = BasketProduct.new
  	@types = ProductsType.all
  end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
   def create
       # emailを受け取る処理
      @member = Member.find_by(email: params[:member][:email].downcase)
      # emailで存在しているか調べる
      if @member
          if (@member.valid_password?(params[:member][:password]) && (@member.member_status == true))
            flash[:error] = "退会済みです。"
            redirect_to new_member_session_path
          else
            super
          end
      else
          flash[:error] = "必須項目を入力してください。"
          redirect_to new_member_session_path
      end
   end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/members_helper.rb
module Admins::MembersHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/members/baskets_helper.rb
module Members::BasketsHelper
end

app/helpers/members/destinations_helper.rb
module Members::DestinationsHelper
end

app/views/members/orders/confirm.html.erb
<div class="container">
	<div class="row">
		<h2>注文情報確認</h2>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<table class="table table-bordered">
				<tr class="active">
					<th>商品名</th>
					<th>単価(税込)</th>
					<th>数量</th>
					<th>小計</th>
				</tr>
				<!-- カート商品でeach文 -->
				<% current_member.basket_products.each do |pro| %>
					<tr>
						<td><%= pro.product.name %></td>
						<td><%= (pro.product.unit_price * 1.1).round.to_s(:delimited, delimiter: ',') %></td>
						<td><%= pro.quantity %></td>
						<td><%= (pro.product.unit_price * pro.quantity * 1.1).round.to_s(:delimited, delimiter: ',') %></td>
						<% @price_array << pro.quantity %>
						<% @total_array << pro.product.unit_price * pro.quantity %>
					</tr>
				<% end %>
			</table>
		</div>
		<div class="col-xs-12">
			<table class="table table-bordered">
				<tr>
					<td class="active">送料</td>
					<td>800</td>
				</tr>
				<tr>
					<td class="active">商品合計</td>
					<td><%= (@total_array.sum * 1.1).round.to_s(:delimited, delimiter: ',') %></td>
				</tr>
				<tr>
					<td class="active">請求金額</td>
					<td><%= (@total_array.sum * 1.1 + 800).round.to_s(:delimited, delimiter: ',') %></td>
				</tr>
			</table>
		</div>
		<div>
			<table class="table table-bordered">
				<tr>
					<td class="active">支払い方法</td>
					<td>
						<%if @order.payment_method == true %>
							クレジットカード
						<% else %>
							銀行振込
						<% end %>
					</td>
				</tr>
				<tr>
					<td class="active">お届け先</td>
					<td>
						<%= "#{@post} #{@address} #{@name}" %>
					</td>
				</tr>
			</table>
		</div>
		<div>
			<%= form_for(@order, url: members_orders_path, method: :post) do |f| %>
				<%= f.hidden_field :payment_method, value: @order.payment_method %>
				<%= f.hidden_field :post_address, value: @post %>
				<%= f.hidden_field :address, value: @address %>
				<%= f.hidden_field :full_name, value: @name %>
				<%= f.hidden_field :request_amount, value: @total_array.sum %>
				<%= f.hidden_field :member_id, value: current_member.id %>
				<%= f.submit "購入を確定する", class: "btn btn-success" %>
			<% end %>
		</div>
	</div>
</div>

app/views/members/orders/index.html.erb
<div class="container">
	<div class="row">
		<h2>注文履歴一覧</h2>
	</div>
	<div class="row">
		<div class="col-xs-12 offset-2">
			<table class="table">
				<thead>
					<tr>
						<th>注文日</th>
						<th>配送先</th>
						<th>注文商品</th>
						<th>支払金額</th>
						<th>ステータス</th>
						<th>注文詳細</th>
					</tr>
				</thead>
				<tbody>
					<% @order.each do |order| %>
						<tr>
							<td><%= order.created_at.strftime('%Y/%m/%d') %></td>
							<td>
								<%= order.post_address %><br>
								<%= order.address %><br>
								<%= order.full_name %>
							</td>
							<td>
								<% order.order_products.each do |order_product| %>
									<%= "#{order_product.product.name}," %>
								<% end %>
							</td>
							<td><%= (order.request_amount * 1.1).round.to_s(:delimited, delimiter: ',') %>円</td>
							<td><%= order.order_status %></td>
							<td><%= link_to "表示する", members_order_path(order.id), class: "btn btn-primary" %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/members/orders/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12 offset-3">
			<h2>注文情報入力</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<%= form_with url: members_orders_confirm_path, method: :post, local: true do |form| %>
				<table>
					<thead>
						<h3>支払い方法</h3>
					</thead>
					<tbody class="col-xs-12">
						<tr>
							<td>
								<%= form.radio_button :payment_method, :true, checked: true %>
								<%= form.label :payment_method, "クレジットカード",  style: "display: inline-block;" %>
							</td>
						</tr>
						<tr>
							<td>
								<%= form.radio_button :payment_method, :false %>
								<%= form.label :payment_method, "銀行振込", style: "display: inline-block;" %>
							</td>
						</tr>
					</tbody>
				</table>

				<table>
					<thead>
						<h3>お届け先</h3>
					</thead>
					<tbody class="col-xs-12">
						<tr>
							<td>
								<%= form.radio_button :address_option, 0 %>
								<%= form.label :ご自身の住所, class: "display: inline-block;" %>
							</td>
						</tr>
						<tr class="col-xs-12">
							<td>
								<%= "#{current_member.post_number} #{current_member.address} #{current_member.last_name}#{current_member.first_name}" %>
							</td>
						</tr>
						<tr>
							<td>
								<%= form.radio_button :address_option, 1 %>
								<%= form.label :登録済住所から選択, class: "display: inline-block;" %>
							</td>
						</tr>
						<tr class="col-xs-12">
							<td>
								<%= form.select :id , Destination.all.map {|e| [e.full_address, e.id] } %>
							</td>
						</tr>
						<tr>
							<td>
								<%= form.radio_button :address_option, 2 %>
								<%= form.label :新しいお届け先, class: "display: inline-block;" %>
							</td>
						</tr>
						<tr class="col-xs-12">
							<td>
								<%= form.label :post_address, "郵便番号" %>
								<%= form.text_field :post_address %>
							</td>
						</tr>
						<tr class="col-xs-12">
							<td>
								<%= form.label :address, "住所" %>
								<%= form.text_field :address %>
							</td>
						<tr class="col-xs-12">
							<td>
								<%= form.label :full_name, "宛名" %>
								<%= form.text_field :full_name %>
							</td>
						</tr>
						<tr>
							<td>
								<%= form.submit "確認画面へ進む", class: "btn btn-primary" %>
							</td>
						</tr>
					</tbody>
				</table>
			<% end %>
		</div>
	</div>
</div>

app/views/members/orders/show.html.erb
<div class="container">
	<div class="row">
		<h2>注文履歴詳細</h2>
	</div>
	<div class="row">
		<div class="col-xs-6">
			<p>注文情報</p>
			<table class="table table-bordered">
				<tr>
					<td class="active">注文日</td>
					<td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
				</tr>
				<tr>
					<td class="active">配送先</td>
					<td>
						<%= @order.post_address %><br>
						<%= @order.address %><br>
						<%= @order.full_name %>
					</td>
				</tr>
				<tr>
					<td class="active">支払方法</td>
					<td>
						<%if @order.payment_method == true %>
							クレジットカード
						<% else %>
							銀行振込
						<% end %>
					</td>
				</tr>
				<tr>
					<td class="active">ステータス</td>
					<td><%= @order.order_status %></td>
				</tr>
			</table>
		</div>
		<div class="col-xs-6">
			<p>請求情報</p>
			<table class="table table-bordered">
				<tr>
					<td class="active">商品合計</td>
					<td><%= (@order.order_products.sum(:price_at_purchase) * 1.1).round.to_s(:delimited, delimiter: ',') %>円</td>
				</tr>
				<tr>
					<td class="active">配送料</td>
					<td>800円</td>
				</tr>
				<tr>
					<td class="active">ご請求額</td>
					<td><%= (@order.order_products.sum(:price_at_purchase) * 1.1 + 800).round.to_s(:delimited, delimiter: ',') %>円</td>
				</tr>
			</table>
		</div>
	</div>
	<div class="row">
		<p>注文内容</p>
		<table class="table table-bordered">
			<thead>
				<tr class="active">
					<th>商品</th>
					<th>単価(税込)</th>
					<th>個数</th>
					<th>小計</th>
				</tr>
			</thead>
			<tbody>
				<% @order.order_products.each do |pro| %>
					<tr>
						<td><%= pro.product.name %></td>
						<td><%= (pro.product.unit_price * 1.1).round.to_s(:delimited, delimiter: ',') %></td>
						<td><%= pro.quantity_purchased %></td>
						<td><%= (pro.price_at_purchase * 1.1).round.to_s(:delimited, delimiter: ',') %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/members/orders/success.html.erb
<div class="success" style="text-align: center;, vertical-align: middle;">
	<h2>ご購入ありがとうございました！</h2>
</div>