config/routes.rb
Rails.application.routes.draw do

  root 'members/homes#top'

  namespace :members do
    resources :destinations, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :show, :new, :create]
    post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
    get 'success' => 'orders#success', as: 'success'
    delete 'basket_products/alldestroy' => 'basket_products#alldestroy', as: 'basket_products_alldestroy'
    resources :basket_products, only: [:index, :create, :update, :destroy]
    resources :products, only: [:index, :show]
    get 'members/leave' => 'members#leave', as: 'members_leave'
    get 'homes/about' => 'homes#about', as:'homes_about'
    patch "members" => "members#destroy_update"
    resources :members, only: [:show, :edit, :update]
   end

  namespace :admins do
    get 'orders/top' => 'orders#top', as:'orders_top'
    resources :members, only: [:index, :show, :edit, :update]
    resources :productstypes, only: [:index, :edit, :create, :update]
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_products, only: [:update]

  end

  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
  }

  devise_for :members, controllers: {
      sessions:      'members/sessions',
      passwords:     'members/passwords',
      registrations: 'members/registrations'
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :member, optional: true
	has_many :order_products, dependent: :destroy
	
	enum order_status: {
		入金待ち: 0,
		入金確認: 1,
		製作中: 2,
		発送準備中: 3,
		発送済み: 4
	}
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  def top
    @order = Order.all
  end

  def index
  	@order = Order.page(params[:page])
  end

  def show
  	@order = Order.find(params[:id])
  end

  def update
  	@order = Order.find(params[:id])
  	@order.update(order_params)
    if @order.order_status == "入金確認"
      @order.order_products.each do |op|
        op.update(production_status: 1)
      end
    end
   	redirect_to admins_order_path(@order.id)
  end

  private
	def order_params
		params.require(:order).permit(:order_status)
	end
end

app/controllers/members/orders_controller.rb
class Members::OrdersController < ApplicationController
  def index
    @order = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order_new = Order.new
    @members = Member.all
    @dest = Destination.new
  end

  def create
    @order = Order.new(order_set)
    if @order.save!
      current_member.basket_products.each do |basket|
        @price = basket.product.unit_price * basket.quantity
        @order_products = OrderProduct.new(
          product_id: basket.product.id,
          quantity_purchased: basket.quantity,
          price_at_purchase: @price,
          order_id: @order.id)
        
        @order_products.save!
      end
      current_member.basket_products.destroy_all
    end
    redirect_to members_success_path
  end

  def confirm
    @price_array = []
    @total_array = []
    @order = Order.new
    if params[:payment_method] == 'true'
      @order.payment_method = true
    else
      @order.payment_method = false
    end
    @user = Member.find(current_member.id)

    if params[:address_option] == "0"
      @post = @user.post_number
      @address = @user.address
      @name = @user.last_name + @user.first_name
    elsif params[:address_option] == "1"
      @destination = Destination.find(dest_set[:id])
      @post = @destination.post_address
      @address = @destination.address
      @name = @destination.full_name
    elsif params[:address_option] == "2"
      @new_destination = Destination.new(dest_params)
      @post = @new_destination.post_address
      @address = @new_destination.address
      @name = @new_destination.full_name

      @destination = Destination.new(
        member_id: current_member.id,
        address: @post,
        post_address: @address,
        full_name: @name)
      @destination.save!
    end
  end

  def success
  end

  private
  def order_set
    params.require(:order).permit(:member_id, :request_amount, :payment_method, :address, :post_address, :full_name)
  end

  def dest_set
    params.permit(:id)
  end

  def dest_params
    params.permit(:member_id, :address, :post_address, :full_name)
  end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/members/orders_helper.rb
module Members::OrdersHelper
end

app/views/admins/orders/index.html.erb
<div class=“container”>
  <div class=“row”>
    <div class="col-md-6 col-md-offset-1">
      <h4><strong>注文履歴一覧</strong></h4>
    </div>
  </div>

	<div class="row">
    <div class="col-md-8 col-md-offset-2">
      <table class="table">
        <thead>
          <tr class="active">
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.each do |order| %>
            <tr>
              <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admins_order_path(order.id) %></td>
              <td><%= "#{order.member.last_name} #{order.member.first_name}" %></td>
              <td><%= order.order_products.sum(:quantity_purchased) %></td>
              <td><%= order.order_status %></td>
            </tr>
          <% end %>
          <%= paginate @order %>
        </tbody>
      </table>

    </div>
    <!-- col -->
  </div>
  <!-- row -->
    
</div>
<!-- container -->

app/views/admins/orders/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-1">
			<h4><strong>注文履歴詳細</strong></h4>
		</div>
	</div>

	<div class="row">
		<div class="col-md-9">
			<h1>  </h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-7">
			<table class="table">
				<tbody>
					<tr>
						<th>購入者</th>
						<td><%= link_to "#{@order.member.last_name} #{@order.member.first_name}", admins_member_path(@order) %></td>
					</tr>
					<tr>
						<th>配送先</th>
						<td> 〒<%=  @order.post_address%> <%= @order.address %></td>
					</tr>
					<tr>
						<td> </td>
						<td><%= @order.full_name %></td>
					</tr>
					<tr>
						<th>支払い方法</th>
						<td>
							<%if @order.payment_method == true %>
								クレジットカード
							<% else %>
								銀行振込
							<% end %>
						</td>
					</tr>
					<tr>
						<th>注文ステータス</th>
						<%= form_for(@order, url: admins_order_path(@order)) do |f| %>
							<td><%= f.select :order_status, Order.order_statuses.keys.to_a %>
								<%= f.submit '更新', class: "btn btn-primary" %>
							</td>
						<% end %>
					</tr>

				</tbody>
			</table>
		</div>
	</div>
	<!-- row -->

	<div class="row">
		<div class="col-md-9">
			<h1>  </h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8">
			<table class="table">
				<thead>
					<tr class="active">
						<th>商品名</th>
						<th>単価(税込)</th>
						<th>数量</th>
						<th>小計</th>
						<th>制作ステータス</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @order.order_products.each do |pro| %>
						<tr>
							<td><%= pro.product.name %></td>
							<td><%= (pro.product.unit_price * 1.1).round.to_s(:delimited, delimiter: ',') %></td>
							<td><%= pro.quantity_purchased %></td>
							<td><%= (pro.product.unit_price * pro.quantity_purchased * 1.1).round.to_s(:delimited, delimiter: ',') %></td>
							<%= form_for(pro,url: admins_order_product_path(pro.id)) do |f| %>
								<td><%= f.select :production_status, OrderProduct.production_statuses.keys.to_a %>
									<%= f.submit '更新ボタン', class: "btn btn-primary" %>
								</td>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<!-- col -->

		<table>

			<tr>
				<th>商品合計</th>
				<td><%= (@order.order_products.sum(:price_at_purchase) * 1.1).round.to_s(:delimited, delimiter: ',') %>円</td>
			</tr>
			<tr>
				<th>送料</th>
				<td>800円</td>
			</tr>
			<tr>
				<th>請求金額合計</th>
				<td><%= (@order.order_products.sum(:price_at_purchase) * 1.1 + 800).round.to_s(:delimited, delimiter: ',') %>円</td>
			</tr>
		</table>
	</div>
	<!-- row -->
</div>
<!-- container -->

app/views/admins/orders/top.html.erb
<div class="container">

	<div class="row">
		<div class="col-md-6 col-md-offset-1">
			<h5><strong>管理者画面</strong></h5>
		</div>
	</div>

	<div class="row">
		<div class="col-md-2">
			<h4>本日の注文件数</h4>
		</div>
		<div class="col-md-4 col-md-offset-1">
			<h4>本日の注文件数 <%= link_to @order.count, admins_orders_path %>件</h4>
		</div>
	</div>


</div>